import 'package:flutter/foundation.dart';
import 'package:flutter_test/flutter_test.dart';

import 'test_helpers.dart';

void main() {
  test('paragraph renders the expected widget tree', () {
    const markdown = '# A `B` C';

    final actual = renderMarkdownToDebugString(
      markdown,
      selectable: true,
      minDiagnosticLevel: DiagnosticLevel.hidden,
    );

    const expected = 'block: 1\n'
        'Text(null,\n'
        ' ╞═╦══ textSpan ═══\n'
        '   ║ TextSpan:\n'
        '   ║   debugLabel: (blackMountainView headlineMedium).apply\n'
        '   ║   inherit: true\n'
        '   ║   color: Color(alpha: 1.0000, red: 0.1137, green: 0.1059, blue:\n'
        '   ║     0.1255, colorSpace: ColorSpace.sRGB)\n'
        '   ║   backgroundColor: null\n'
        '   ║   family: Roboto\n'
        '   ║   familyFallback: null\n'
        '   ║   size: null\n'
        '   ║   weight: null\n'
        '   ║   style: null\n'
        '   ║   letterSpacing: null\n'
        '   ║   wordSpacing: null\n'
        '   ║   baseline: null\n'
        '   ║   height: null\n'
        '   ║   leadingDistribution: null\n'
        '   ║   locale: null\n'
        '   ║   foreground: null\n'
        '   ║   background: null\n'
        '   ║   decorationColor: Color(alpha: 1.0000, red: 0.1137, green: 0.1059,\n'
        '   ║     blue: 0.1255, colorSpace: ColorSpace.sRGB)\n'
        '   ║   decoration: TextDecoration.none\n'
        '   ║   decoration: Color(alpha: 1.0000, red: 0.1137, green: 0.1059,\n'
        '   ║     blue: 0.1255, colorSpace: ColorSpace.sRGB) TextDecoration.none\n'
        '   ║   decorationThickness: null\n'
        '   ║   null\n'
        '   ║   recognizer: null\n'
        '   ║   callbacks\n'
        '   ║   mouseCursor: defer\n'
        '   ║   TextSpan:\n'
        '   ║     debugLabel: (blackMountainView headlineMedium).apply\n'
        '   ║     inherit: true\n'
        '   ║     color: Color(alpha: 1.0000, red: 0.1137, green: 0.1059, blue:\n'
        '   ║       0.1255, colorSpace: ColorSpace.sRGB)\n'
        '   ║     backgroundColor: null\n'
        '   ║     family: Roboto\n'
        '   ║     familyFallback: null\n'
        '   ║     size: null\n'
        '   ║     weight: null\n'
        '   ║     style: null\n'
        '   ║     letterSpacing: null\n'
        '   ║     wordSpacing: null\n'
        '   ║     baseline: null\n'
        '   ║     height: null\n'
        '   ║     leadingDistribution: null\n'
        '   ║     locale: null\n'
        '   ║     foreground: null\n'
        '   ║     background: null\n'
        '   ║     decorationColor: Color(alpha: 1.0000, red: 0.1137, green: 0.1059,\n'
        '   ║       blue: 0.1255, colorSpace: ColorSpace.sRGB)\n'
        '   ║     decoration: TextDecoration.none\n'
        '   ║     decoration: Color(alpha: 1.0000, red: 0.1137, green: 0.1059,\n'
        '   ║       blue: 0.1255, colorSpace: ColorSpace.sRGB) TextDecoration.none\n'
        '   ║     decorationThickness: null\n'
        '   ║     "A "\n'
        '   ║     recognizer: null\n'
        '   ║     callbacks\n'
        '   ║     mouseCursor: defer\n'
        '   ║   TextSpan:\n'
        '   ║     debugLabel: (((blackMountainView\n'
        '   ║       headlineMedium).apply).merge(((blackMountainView\n'
        '   ║       bodyMedium).apply).copyWith)).copyWith\n'
        '   ║     inherit: true\n'
        '   ║     color: Color(alpha: 1.0000, red: 0.1137, green: 0.1059, blue:\n'
        '   ║       0.1255, colorSpace: ColorSpace.sRGB)\n'
        '   ║     backgroundColor: Color(alpha: 1.0000, red: 0.9333, green: 0.9333,\n'
        '   ║       blue: 0.9333, colorSpace: ColorSpace.sRGB)\n'
        '   ║     family: monospace\n'
        '   ║     familyFallback: null\n'
        '   ║     size: null\n'
        '   ║     weight: null\n'
        '   ║     style: null\n'
        '   ║     letterSpacing: null\n'
        '   ║     wordSpacing: null\n'
        '   ║     baseline: null\n'
        '   ║     height: null\n'
        '   ║     leadingDistribution: null\n'
        '   ║     locale: null\n'
        '   ║     foreground: null\n'
        '   ║     background: null\n'
        '   ║     decorationColor: Color(alpha: 1.0000, red: 0.1137, green: 0.1059,\n'
        '   ║       blue: 0.1255, colorSpace: ColorSpace.sRGB)\n'
        '   ║     decoration: TextDecoration.none\n'
        '   ║     decoration: Color(alpha: 1.0000, red: 0.1137, green: 0.1059,\n'
        '   ║       blue: 0.1255, colorSpace: ColorSpace.sRGB) TextDecoration.none\n'
        '   ║     decorationThickness: null\n'
        '   ║     "B"\n'
        '   ║     recognizer: null\n'
        '   ║     callbacks\n'
        '   ║     mouseCursor: defer\n'
        '   ║   TextSpan:\n'
        '   ║     debugLabel: (blackMountainView headlineMedium).apply\n'
        '   ║     inherit: true\n'
        '   ║     color: Color(alpha: 1.0000, red: 0.1137, green: 0.1059, blue:\n'
        '   ║       0.1255, colorSpace: ColorSpace.sRGB)\n'
        '   ║     backgroundColor: null\n'
        '   ║     family: Roboto\n'
        '   ║     familyFallback: null\n'
        '   ║     size: null\n'
        '   ║     weight: null\n'
        '   ║     style: null\n'
        '   ║     letterSpacing: null\n'
        '   ║     wordSpacing: null\n'
        '   ║     baseline: null\n'
        '   ║     height: null\n'
        '   ║     leadingDistribution: null\n'
        '   ║     locale: null\n'
        '   ║     foreground: null\n'
        '   ║     background: null\n'
        '   ║     decorationColor: Color(alpha: 1.0000, red: 0.1137, green: 0.1059,\n'
        '   ║       blue: 0.1255, colorSpace: ColorSpace.sRGB)\n'
        '   ║     decoration: TextDecoration.none\n'
        '   ║     decoration: Color(alpha: 1.0000, red: 0.1137, green: 0.1059,\n'
        '   ║       blue: 0.1255, colorSpace: ColorSpace.sRGB) TextDecoration.none\n'
        '   ║     decorationThickness: null\n'
        '   ║     " C"\n'
        '   ║     recognizer: null\n'
        '   ║     callbacks\n'
        '   ║     mouseCursor: defer\n'
        ' , textAlign: null, textDirection: null, locale: null, softWrap: null, overflow: null, textScaleFactor: null, maxLines: null, textWidthBasis: null, textHeightBehavior: null)';

    expect(actual, expected);
  });
}
